import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

type Log = {
  author: string;
  title: string;
  text: string;
};
type Props = {
  logs: Log[];
};

export const getStaticProps: GetStaticProps<Props> = async (context) => {
  return {
    props: {
      logs: [
        {
          author: "Romelianism",
          title: "Life",
          text: "Hi this is life!",
        },
      ],
    }, // will be passed to the page component as props
    revalidate: 10,
  };
};

const Home: NextPage<Props> = ({ logs }) => {
  console.log(logs);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Link href="/account">
          <a>
            <span>Writealog</span>
          </a>
        </Link>
        <input />
        <Link href="/account">
          <a>
            <span>Account</span>
          </a>
        </Link>
      </header>

      <main className={styles.main}>
        <h1>All Logs</h1>
        <ul>
          {logs.map(({ author, title, text }) => {
            const link = `${author}/${title}`;
            return (
              <li key={link}>
                <div>
                  <Link href={link}>
                    <a>
                      <h3>{title}</h3>
                      <p>{text}</p>
                    </a>
                  </Link>
                  <Link href={author}>{author}</Link>
                </div>
                <div>
                  <button>favorite</button>
                  <button>like</button>
                  <button>...</button>
                </div>
              </li>
            );
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <nav>
          <Link href="/">Home</Link>
          <Link href="/favorites">Favorites</Link>
          <Link href="/following">Following</Link>
        </nav>
      </footer>
    </>
  );
};

export default Home;
